name: Build and Release

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: actions/checkout@v3
      - name: cd
        run: cd weather-app 
      - name: Install dependencies
        run: npm install
        working-directory: ./weather-app
      - name: Build the app
        run: npm run build
        working-directory: ./weather-app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
        working-directory: ./weather-app
